version: '3'

services:

  database:
    container_name: flask_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: darya
      POSTGRES_DB: flask_db
    volumes:
      - ./date_postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    container_name: ex
    image: dybashka/ex
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - database
