version: '3'

services:

  database:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./date_postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    container_name: ex
    image: daryabalashova/ex:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - database
